name: Banking UI Tests

on:
  push:
    branches:
      - master
      - main
      - task_ui

jobs:
  individual-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-file:
          - test_add_customer.py
          - test_customer_sorting.py
          - test_delete_customer.py

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run individual test
        run: |
          python -m pytest tests/${{ matrix.test-file }} -v --alluredir=allure-results-${{ matrix.test-file }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.test-file }}
          path: allure-results-${{ matrix.test-file }}

  parallel-tests:
    runs-on: ubuntu-latest
    needs: individual-tests

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-xdist

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run tests in parallel
        run: |
          python -m pytest tests/ -v -n 3 --alluredir=allure-results-parallel

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-parallel
          path: allure-results-parallel