name: Banking UI Tests CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      test-tags:
        description: 'Pytest tags to run (e.g., smoke, regression)'
        required: false
        type: string
        default: ''
      browser-mode:
        description: 'Browser visibility mode'
        required: true
        default: 'headless'
        type: choice
        options:
        - headless
        - headed
      extra-args:
        description: 'Extra pytest arguments'
        required: false
        type: string
        default: '-v -s'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        echo "Chrome installed:"
        google-chrome --version

    - name: Run tests
      run: |
        pytest tests/ ${{ github.event.inputs.extra-args }} --alluredir=allure-results

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: allure-results
        retention-days: 30